# Site settings
baseurl = "http://yourfriendjeff.com/"
languageCode = "en-us"
title = "jeff souza (software engineer)"
theme = "hugrid"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-100666835-1"

contentdir = "content"
datadir = "data" layoutdir = "layouts"
publishdir = "docs"

[params]
    # Meta
    title = "jeff souza (software engineer)"
    subtitle = "[my résumé](/resume_cv.pdf)"
    author = "jeff souza"
    description = "my personal site"
    keywords = "jeff souza, game development, portfolio, software, engineer"

    # Body background color
    bodybgcolor = "#F2F2F2"

    # Preview container button text
    buttontext = "Check it out"

    # Footer text
    footertext = "[github](https://github.com/JeffreySouza) -  [linkedin](https://www.linkedin.com/in/jeffreysouza/) -  [twitter](https://twitter.com/1inchboy) -  [email](mailto:jeffreymsouza@gmail.com)"

    # add extra-css
    custom_css = ['css/extra.css']
